services:
  league-bot:
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      RIOT_TOKEN: ${RIOT_TOKEN}
      OWNER_DISCORD_ID: ${OWNER_DISCORD_ID}
      FILES_PATH: ${FILES_PATH}
      API_THREADS: 2
      SERVER: "euw1"
      REGION: "europe"
